services:
  maddy:
    image: enwaiax/maddy:0.9.5
    restart: unless-stopped
    environment:
      MADDY_HOSTNAME: ${MADDY_HOSTNAME:?set MADDY_HOSTNAME}
      MADDY_DOMAIN: ${MADDY_DOMAIN:?set MADDY_DOMAIN}
    volumes:
      - maddydata:/data
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  maddydata:
    name: maddydata
