services:
  nginx:
    image: nginx:alpine
    restart: on-failure
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./rainloop:/usr/share/nginx/html:ro
      - ./rainloop.conf:/etc/nginx/conf.d/default.conf:ro
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  php:
    image: php:8.1.6RC1-fpm-alpine3.15
    restart: on-failure
    volumes:
      - ./rainloop:/var/www/html
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
