services:
  xui:
    image: enwaiax/x-ui:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./db:/etc/x-ui
      - ./cert:/root/cert:ro
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
